# SonarCloud configuration for LOTUSim
# https://docs.sonarsource.com/sonarcloud/advanced-setup/ci-based-analysis/sonarscanner-for-dotnet/

sonar.projectKey=cmoron_LOTUSim
sonar.organization=cmoron

sonar.sources=systems,interfaces
sonar.sourceEncoding=UTF-8

# C++ analysis with build-wrapper
sonar.cfamily.compile-commands=build/compile_commands.json

# Exclusions
sonar.exclusions=**/test/**,**/build/**,**/install/**,**/log/**
